os: linux
language: node_js
node_js:
  - "4.6"
before_script:
  - npm install -g gulp
script: gulp tests

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - build-essential
      - libudev-dev
      - clang-3.3
      - fakeroot
      - git
      - libgnome-keyring-dev
      - g++-4.8
env:
  - CXX=g++-4.8

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm -v
  - npm install
