language: node_js
node_js:
  - "4.4"
before_script:
  - npm install -g gulp
script: gulp tests

addons:
  apt:
    packages:
      - xvfb
      - build-essential

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm -v
  - npm install
