os: linux
language: node_js
node_js:
  - "4.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - build-essential
      - libudev-dev
      - clang-3.3
      - fakeroot
      - git
      - libgnome-keyring-dev
      - g++-4.8
env:
  - CXX=g++-4.8

before_install: 
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g gulp
install:
  - npm -v
  - npm install

before_script:
  - export DISPLAY=':99.0'
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: gulp tests
