image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn

build_script:
  - yarn run release:windows

test: off

artifacts:
  - path: 'dist-package\*.exe'
    name: 'Picturama package'
